language: erlang

env:
  - LUA="th"

branches:
  only:
    - master

before_script:
  - export PATH=$PATH:/usr/local/bin/
  - sudo apt-get update -qq >/dev/null
  - sudo apt-get install -qq gfortran  >/dev/null
  - sudo apt-get install -qq  gcc-multilib gfortran-multilib  >/dev/null
  - sudo apt-get install -qq liblapack-dev >/dev/null
  - sudo pip install virtualenv
  - curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-all | bash
  - echo "==== Building torch-dokx, using luarocks ===="
  - sudo /usr/local/bin/luarocks make
  - echo "==== Building torch-dokx with documentation, using doxk-luarocks ===="
  - sudo /usr/local/bin/dokx-luarocks make

script: 'for x in tests/test*.lua ; do echo "==== $x ====" ; th $x ; done'

notifications:
  email:
    on_success: change
    on_failure: always
